name: smart_care_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
